apiVersion: v1
kind: Service
metadata:
  name: webappdockerdemo-service 
spec:
  selector:
    app: webappdockerdemo
  ports:
  - protocol: "TCP"
    port: 32412
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappdockerdemo-service 
  labels:
    app: webappdockerdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webappdockerdemo
  template:
    metadata:
      labels:
        app: webappdockerdemo
    spec:
      containers:
      - name: webappdockerdemo-container
        image: mackdocker/webappdockerdemo
        imagePullPolicy: Never
        ports:
        - containerPort: 80